[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Embedder-Policy = "unsafe-none"

[[redirects]]
  from = "/__/firebase/*"
  to = "https://dailyz-a3b19.firebaseapp.com/__/firebase/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/__/auth/*"
  to = "https://dailyz-a3b19.firebaseapp.com/__/auth/:splat"
  status = 200
  force = true